
# 
# Copyright (C) 2020 ArtXIA <https://github.com/artxia>
# <https://github.com/artxia/Action-NotionSite.git>
#

name: Deploy to Pages

on:
#  schedule:
#    - cron: "*/20 * * * *"
  workflow_dispatch:
    inputs:
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Checkout loconotion
        uses: actions/checkout@v3
        with:
          repository: leoncvlt/loconotion
          path: loconotion

      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          path: pages_repo

      - name: Build Loconotion docker image
        run: docker-compose build loconotion
        working-directory: loconotion

      - name: Configuration File
        run: |
          cat >  ${GITHUB_WORKSPACE}/loconotion/example/example_site.toml  << EOF
          ${{ secrets.SITE_CONFIG }}
          EOF

      - name: Run Loconotion
        run: |
          docker-compose run \
          -v "${GITHUB_WORKSPACE}/pages_repo/dist:/app/loconotion/dist" \
          -v "${GITHUB_WORKSPACE}/loconotion/example/example_site.toml:/app/loconotion/site.toml" \
          loconotion "site.toml"
        working-directory: loconotion
